@CharacterForge_Api = http://localhost:5154

GET {{CharacterForge_Api}}/health
Accept: application/json

###

GET {{CharacterForge_Api}}/api/meta
Accept: application/json

###

GET {{CharacterForge_Api}}/api/catalog/classes?pageSize=12
Accept: application/json

###

GET {{CharacterForge_Api}}/api/catalog/spells?level=3&school=evocation&class=wizard&sort=level
Accept: application/json

###

GET {{CharacterForge_Api}}/api/catalog/spells/fireball
Accept: application/json

###

POST {{CharacterForge_Api}}/api/characters/validate
Content-Type: application/json

{
  "id": "f33771b4-ae75-47b6-bad0-df2a80896a67",
  "name": "Arannis",
  "ruleset": "2024",
  "rulesVersion": "SRD-5.2.1",
  "abilities": {
    "strength": 8,
    "dexterity": 14,
    "constitution": 13,
    "intelligence": 12,
    "wisdom": 10,
    "charisma": 16
  },
  "species": { "id": "elf", "name": "Elf" },
  "background": { "id": "acolyte", "name": "Acolyte" },
  "classProgressions": [
    {
      "class": { "id": "wizard", "name": "Wizard" },
      "level": 1
    }
  ],
  "proficiencyChoices": [
    {
      "choiceId": "classes/wizard/proficiencies/0",
      "selections": [
        { "id": "skill-arcana", "name": "Skill: Arcana" },
        { "id": "skill-history", "name": "Skill: History" }
      ]
    },
    {
      "choiceId": "species/elf/traits/keen-senses/proficiencies/0",
      "selections": [
        { "id": "skill-perception", "name": "Skill: Perception" }
      ]
    }
  ]
}
